# Generated by Django 3.2.3 on 2022-02-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0030_auto_20220127_1216'),
        ('bipApp', '0031_project_path'),
    ]

    operations = [
    ]
