# Generated by Django 3.2.4 on 2022-02-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependency_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('companyname', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('interests_dep', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate_dep', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('spouse_dep', models.CharField(blank=True, max_length=255, null=True)),
                ('children_dep', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(blank=True, null=True, verbose_name='date submitted')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('markup', models.FloatField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(verbose_name='date transacted')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'Ledger_Entries',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('risk_management', models.TextField(blank=True, null=True)),
                ('roles', models.TextField(blank=True, null=True)),
                ('quality_assurance', models.TextField(blank=True, null=True)),
                ('communication', models.TextField(blank=True, null=True)),
                ('resources', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('path', models.CharField(max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='date purchased')),
                ('total', models.FloatField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('sub_date', models.DateField(blank=True, verbose_name='date referenced')),
                ('opening', models.BooleanField(blank=True, default=False, null=True)),
                ('closing', models.BooleanField(blank=True, default=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('start', models.DateTimeField(verbose_name='start date')),
                ('end', models.DateTimeField(verbose_name='end date')),
                ('opening', models.BooleanField(blank=True, default=False, null=True)),
                ('closing', models.BooleanField(blank=True, default=False, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('debit', models.BooleanField(verbose_name='date transacted')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.ledger_entry')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Clock_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.ledger_entry')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
            options={
                'verbose_name_plural': 'Time_Clock_Entries',
            },
        ),
        migrations.CreateModel(
            name='Task_Supporting_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('filetype', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Supporting_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('filetype', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.task'),
        ),
        migrations.CreateModel(
            name='Receipt_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.receipt')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_Line_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True)),
                ('quantity', models.FloatField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.receipt')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.receipt_status'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity'),
        ),
        migrations.CreateModel(
            name='Project_Supporting_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('filetype', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Supporting_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('filetype', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.item_category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item_category'),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity'),
        ),
        migrations.CreateModel(
            name='Invoice_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.invoice')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Line_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True)),
                ('quantity', models.FloatField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.invoice_status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hired', models.DateField(blank=True, null=True, verbose_name='date hired')),
                ('ssn', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='bipApp.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='bipApp.task')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.dependency_type')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthdate')),
                ('path', models.CharField(max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='bipApp.entity')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.customer_status')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.question')),
            ],
        ),
    ]
