# Generated by Django 3.2.3 on 2021-05-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('plan_ref', models.CharField(max_length=200)),
                ('justification', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('schedule', models.TextField(blank=True)),
                ('risk_management', models.TextField(blank=True)),
                ('roles', models.TextField(blank=True)),
                ('quality_assurance', models.TextField(blank=True)),
                ('communication_plan', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('start', models.DateTimeField(verbose_name='start date')),
                ('end', models.DateTimeField(verbose_name='end date')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('start', models.DateTimeField(verbose_name='start date')),
                ('end', models.DateTimeField(verbose_name='end date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('start', models.DateTimeField(verbose_name='start date')),
                ('end', models.DateTimeField(verbose_name='end date')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
                ('predecessor', models.ManyToManyField(blank=True, related_name='_bipApp_task_predecessor_+', to='bipApp.Task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.project')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.dependency_type')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Clock_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('start', models.DateTimeField(verbose_name='start date')),
                ('end', models.DateTimeField(verbose_name='end date')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
            options={
                'verbose_name_plural': 'Time_Clock_Entries',
            },
        ),
        migrations.CreateModel(
            name='Task_Supporting_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('filetype', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Supporting_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('filetype', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.task'),
        ),
        migrations.CreateModel(
            name='Project_Supporting_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('filetype', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.question')),
            ],
        ),
    ]
