# Generated by Django 3.2.3 on 2021-06-01 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(verbose_name='date transacted')),
                ('created', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='communication_plan',
            new_name='communication',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='stakeholder',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='project_note',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project_note',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='project_supporting_doc',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project_supporting_doc',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='assignee_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RemoveField(
            model_name='dependency_type',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='closing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='opening',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dependency_type',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='plan_ref',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project_note',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project_supporting_doc',
            name='filetype',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project_supporting_doc',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project_supporting_doc',
            name='path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('debit', models.BooleanField(verbose_name='date transacted')),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.ledger_entry')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='bipApp.task')),
                ('successor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='bipApp.task')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.dependency_type')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account'),
        ),
    ]
