# Generated by Django 3.2.3 on 2021-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0002_auto_20210601_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='entity',
            name='children',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='companyname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='fax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='interests',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='middlename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='spouse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='zip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
