# Generated by Django 3.2.3 on 2021-06-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0003_auto_20210601_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger_entry',
            options={'verbose_name_plural': 'Ledger_Entries'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='report',
            name='end',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start',
        ),
        migrations.AddField(
            model_name='report',
            name='closing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='opening',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
