# Generated by Django 3.2.3 on 2021-06-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0004_auto_20210601_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='report_note',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='report_supporting_doc',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task_note',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task_note',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='task_supporting_doc',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task_supporting_doc',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='time_clock_entry',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='time_clock_entry',
            old_name='report',
            new_name='report_id',
        ),
        migrations.AddField(
            model_name='time_clock_entry',
            name='ledger_entry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.ledger_entry'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report_note',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report_supporting_doc',
            name='filetype',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report_supporting_doc',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task_supporting_doc',
            name='filetype',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task_supporting_doc',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(max_length=255, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hired', models.DateField(verbose_name='date hired')),
                ('ssn', models.CharField(max_length=255, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.customer_status')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity')),
            ],
        ),
    ]
