# Generated by Django 3.2.3 on 2021-06-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0005_auto_20210602_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_clock_entry',
            name='ledger_entry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.ledger_entry'),
        ),
    ]
