# Generated by Django 3.2.3 on 2021-06-03 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0006_alter_time_clock_entry_ledger_entry_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(verbose_name='date submitted')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
                ('cost', models.FloatField(blank=True)),
                ('markup', models.FloatField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='date purchased')),
                ('total', models.FloatField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='report_note',
            old_name='report',
            new_name='report_id',
        ),
        migrations.RenameField(
            model_name='report_supporting_doc',
            old_name='report',
            new_name='report_id',
        ),
        migrations.CreateModel(
            name='Receipt_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.receipt')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_Line_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True)),
                ('quanitity', models.FloatField(blank=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item')),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.receipt')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.receipt_status'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity'),
        ),
        migrations.CreateModel(
            name='Item_Supporting_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('filetype', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item_category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item_category'),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.entity'),
        ),
        migrations.CreateModel(
            name='Invoice_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.invoice')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Line_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True)),
                ('quanitity', models.FloatField(blank=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.invoice')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.item')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.invoice_status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipApp.report'),
        ),
    ]
