# Generated by Django 3.2.3 on 2021-06-03 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0007_auto_20210603_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.RemoveField(
            model_name='item_note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='item_supporting_doc',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ledger_entry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project_note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project_supporting_doc',
            name='created',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created',
        ),
        migrations.RemoveField(
            model_name='report_note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='report_supporting_doc',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task_note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task_supporting_doc',
            name='created',
        ),
        migrations.RemoveField(
            model_name='time_clock_entry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created',
        ),
        migrations.AddField(
            model_name='entity',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='item_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='item_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='ledger_entry',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='project_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='project_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='report_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='report_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='task_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='task_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='time_clock_entry',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
