# Generated by Django 3.2.3 on 2021-06-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0009_auto_20210603_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account'),
        ),
    ]
