# Generated by Django 3.2.3 on 2021-06-03 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0010_alter_vendor_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
