# Generated by Django 3.2.3 on 2021-06-06 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0012_auto_20210603_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 225369, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 260015, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='item_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 261986, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='item_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 263646, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ledger_entry',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 220211, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 235039, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 237042, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 239309, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 240952, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 250979, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='report_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 252777, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='report_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 254710, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 242585, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='task_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 247604, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='task_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 249286, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='time_clock_entry',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 256320, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 32, 35, 222981, tzinfo=utc), verbose_name='date published'),
        ),
    ]
