# Generated by Django 3.2.3 on 2021-06-06 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0013_auto_20210606_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 873936, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 907984, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='item_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 909933, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='item_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 911604, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ledger_entry',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 868734, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 883436, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 885399, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 887621, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 889219, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 899094, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='report_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 900870, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='report_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 902752, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 890852, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='task_note',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 895777, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='task_supporting_doc',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 897419, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='time_clock_entry',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 904340, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 18, 36, 18, 871510, tzinfo=utc), verbose_name='date published'),
        ),
    ]
