# Generated by Django 3.2.3 on 2021-06-12 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0021_rename_quanitity_receipt_line_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
