# Generated by Django 3.2.3 on 2021-06-12 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0024_auto_20210612_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bipApp.account'),
        ),
    ]
