# Generated by Django 3.2.3 on 2021-06-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0025_alter_item_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date submitted'),
        ),
    ]
