# Generated by Django 3.2.4 on 2021-09-26 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0027_invoice_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date referenced'),
            preserve_default=False,
        ),
    ]
