# Generated by Django 3.2.4 on 2021-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0028_report_sub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sub_date',
            field=models.DateField(blank=True, verbose_name='date referenced'),
        ),
    ]
