# Generated by Django 3.2.3 on 2022-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipApp', '0030_auto_20220127_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
